#include "common.h"

struct _EFI_SERVICE_BINDING_PROTOCOL;
typedef EFI_STATUS (EFIAPI *EFI_SERVICE_BINDING_CREATE_CHILD) (
        IN struct _EFI_SERVICE_BINDING_PROTOCOL *This,
        IN OUT EFI_HANDLE *ChildHandle
        );
typedef EFI_STATUS (EFIAPI *EFI_SERVICE_BINDING_DESTROY_CHILD) (
        IN struct _EFI_SERVICE_BINDING_PROTOCOL *This,
        IN EFI_HANDLE ChildHandle
        );
typedef struct _EFI_SERVICE_BINDING_PROTOCOL {
    EFI_SERVICE_BINDING_CREATE_CHILD CreateChild;
    EFI_SERVICE_BINDING_DESTROY_CHILD DestroyChild;
} EFI_SERVICE_BINDING_PROTOCOL;

